import { requireAuthUser } from "@/lib/auth";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { createRequestAction, evaluatePolicyAction, resetSandboxAction, simulateAgentAccessAction, simulateExpirationAction } from "./actions";

export default async function PlaygroundPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
 const params=await searchParams; const user=await requireAuthUser(); const supabase=await createSupabaseServerClient();
 const {data:membership}=await supabase.from("workspace_memberships").select("workspace_id,role").eq("user_id",user.id).limit(1).maybeSingle<{workspace_id:string;role:string}>(); if(!membership) return <main>No workspace membership.</main>;
 const workspaceId=membership.workspace_id; const isAdmin=["owner","admin"].includes(membership.role);
 const [projects,policies,_requests,_grants,audit,agents,scopes]=await Promise.all([
  supabase.from("projects").select("id,name").eq("workspace_id",workspaceId).limit(8),
  supabase.from("capability_policies").select("id,name,effect,priority").eq("workspace_id",workspaceId).eq("enabled",true).order("priority",{ascending:true}).limit(10),
  supabase.from("capability_requests").select("id,status,requested_permission,target_resource_id,created_at").eq("workspace_id",workspaceId).order("created_at",{ascending:false}).limit(12),
  supabase.from("capability_grants").select("id,status,permission,target_resource_id,expires_at").eq("workspace_id",workspaceId).order("created_at",{ascending:false}).limit(12),
  supabase.from("capability_audit_events").select("id,event_type,created_at,actor_user_id,actor_agent_id,event_detail").eq("workspace_id",workspaceId).order("created_at",{ascending:false}).limit(30),
  supabase.from("ai_agents").select("id,name,status").eq("workspace_id",workspaceId).limit(10),
  supabase.from("ai_agent_scopes").select("id,agent_id,permission,resource_id,status,expires_at").eq("workspace_id",workspaceId).limit(12)
 ]);
 return <main className="space-y-6">
 <section className="rounded-3xl border border-cyan-300/20 bg-gradient-to-br from-cyan-900/20 to-slate-900 p-6"><p className="text-xs tracking-[0.25em] uppercase text-cyan-200">Programmable Trust Infrastructure</p><h1 className="text-3xl font-semibold mt-2">Developer Playground</h1><p className="text-slate-300 mt-2">Live sandbox for consent, scoped authority, policy-evaluated actions, and machine governance.</p></section>
 <section className="grid lg:grid-cols-2 gap-4"><form action={createRequestAction} className="rounded-2xl border border-white/10 p-4 bg-white/5 space-y-2"><h2 className="font-semibold">Capability Lifecycle</h2><select name="resourceId" className="w-full rounded border bg-black/20 p-2">{(projects.data??[]).map((p: {id:string;name:string})=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="permission" className="w-full rounded border bg-black/20 p-2"><option>read</option><option>write</option><option>approve</option><option>delegate</option></select><input name="justification" placeholder="Why is this authority needed?" className="w-full rounded border bg-black/20 p-2"/><input type="datetime-local" name="expiresAt" className="w-full rounded border bg-black/20 p-2"/><button className="rounded bg-cyan-500/20 px-3 py-2">Create capability request</button></form>
 <form action={evaluatePolicyAction} className="rounded-2xl border border-white/10 p-4 bg-white/5 space-y-2"><h2 className="font-semibold">Policy Evaluation Visualizer</h2><select name="resourceId" className="w-full rounded border bg-black/20 p-2">{(projects.data??[]).map((p: {id:string;name:string})=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="permission" className="w-full rounded border bg-black/20 p-2"><option>read</option><option>write</option><option>approve</option><option>delegate</option></select><input name="justification" placeholder="Evaluation narrative" className="w-full rounded border bg-black/20 p-2"/><button className="rounded bg-indigo-500/20 px-3 py-2">Run policy decision</button><pre className="text-xs overflow-auto">{String(params.evaluated??"")}</pre></form></section>
 <section className="grid lg:grid-cols-3 gap-4"><article className="rounded-2xl border border-white/10 p-4">Trust Graph: Actor → Policy → Capability → Decision → Audit</article><article className="rounded-2xl border border-white/10 p-4">Policies: {(policies.data??[]).length} active</article><article className="rounded-2xl border border-white/10 p-4">Agent scopes: {(scopes.data??[]).length}</article></section>
 <section className="grid lg:grid-cols-2 gap-4"><form action={simulateAgentAccessAction} className="rounded-2xl border border-white/10 p-4 space-y-2"><h2 className="font-semibold">AI Agent Simulation</h2><select name="agentId" className="w-full rounded border bg-black/20 p-2">{(agents.data??[]).map((a: {id:string;name:string;status:string})=><option key={a.id} value={a.id}>{a.name} ({a.status})</option>)}</select><select name="resourceId" className="w-full rounded border bg-black/20 p-2">{(projects.data??[]).map((p: {id:string;name:string})=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="permission" className="w-full rounded border bg-black/20 p-2"><option>read</option><option>write</option></select><button className="rounded bg-fuchsia-500/20 px-3 py-2">Attempt scoped access</button><pre className="text-xs overflow-auto">{String(params.agent??"")}</pre></form>
 <div className="rounded-2xl border border-white/10 p-4 space-y-2"><h2 className="font-semibold">Sandbox Controls</h2><form action={simulateExpirationAction}><button className="rounded bg-amber-500/20 px-3 py-2">Simulate expiration</button></form>{isAdmin?<form action={resetSandboxAction}><button className="rounded bg-rose-500/20 px-3 py-2">Reset sandbox</button></form>:null}</div></section>
 <section className="rounded-2xl border border-white/10 p-4"><h2 className="font-semibold">Live Audit Timeline</h2><ul className="mt-3 space-y-2 text-sm">{(audit.data??[]).map((e: {id:string;created_at:string;event_type:string;actor_user_id:string|null;actor_agent_id:string|null})=><li key={e.id} className="rounded border border-white/10 p-2"><p>{new Date(e.created_at).toLocaleString()} • {e.event_type}</p><p className="text-slate-400">{e.actor_user_id??e.actor_agent_id??"system"}</p></li>)}</ul></section>
 </main>
}
